# Generated by Django 2.2.1 on 2019-05-05 23:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='koordinat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('titik', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('keterangan', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='polygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('ordinat', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('keterangan', models.CharField(max_length=200)),
            ],
        ),
    ]
