# Generated by Django 2.2.1 on 2019-05-05 23:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lokasi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ruang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('luas', models.CharField(max_length=100)),
                ('distrik', models.CharField(max_length=50)),
                ('kampung', models.CharField(max_length=50)),
            ],
        ),
    ]
